### ISSUE TITLE
output formatter

### ISSUE THREAD

**Issue by marcelloh** [wapmorgan/PhpCodeFixer#13]
Would be nice to make the output configurable.
Like it should understand I want a specified column a bit wider (70 instead of 40)
' %3s | %16s | %70s | %s'

**Comment by wapmorgan** [comment]
I've added automatical adjustment to terminal width. Please, upgrade to developer version (To do this change version in **composer.json** to **dev-master** like this:
```json
    "wapmorgan/php-code-fixer": "dev-master"
```
).

**Comment by marcelloh** [comment]
:-) Sorry, had less time to look for the solution; but it works like a charm :-)
