### ISSUE TITLE
Phar distribution

### ISSUE THREAD

**Issue by borNfreee** [wapmorgan/PhpCodeFixer#17]
it would be great to add Phar distribution for `php-cf` using for example [Box](https://github.com/box-project/box2) project

**Comment by wapmorgan** [comment]
- [ ] Build phar
- [ ] Add self-update command

**Comment by wapmorgan** [comment]
Added *phar* for latest realese (2.0.8): https://github.com/wapmorgan/PhpCodeFixer/releases/download/2.0.8/phpcf.phar

**Comment by wapmorgan** [comment]
Wait, current phar is not valid. Rebuilding it ...

**Comment by wapmorgan** [comment]
Ok, here's a working version: [phar](https://github.com/wapmorgan/PhpCodeFixer/releases/download/2.0.8/phpcf.phar).

**Comment by borNfreee** [comment]
thank you
