### ISSUE TITLE
bin/phpcf: bad interpreter: /usr/bin/php^M: No such file or directory

### ISSUE THREAD

**Issue by dypa** [wapmorgan/PhpCodeFixer#2]
`# git clone git@github.com:wapmorgan/PhpCodeFixer.git`
`# composer install`
`# bin/phpcf` 
`zsh: bin/phpcf: bad interpreter: /usr/bin/php^M: No such file or directory`

**Comment by wapmorgan** [comment]
Hi. Fixed in last commit. Thanks for creating an issue.
