### ISSUE TITLE
Impossible to install the latest version on PHP 7

### ISSUE THREAD

**Issue by EvgenyOrekhov** [wapmorgan/PhpCodeFixer#24]
https://github.com/wapmorgan/PhpCodeFixer/blob/9ccd8f1414069618a3da3a73168ee4fc805de53a/composer.json#L7

The `^` here prevents installations on PHP 7.

It should be changed to `"php": ">=5.4"`.

**Comment by wapmorgan** [comment]
Ooh, sorry, fixing it.

**Comment by wapmorgan** [comment]
Try **2.0.12**.
