### ISSUE TITLE
Version flag

### ISSUE THREAD

**Issue by MetalArend** [wapmorgan/PhpCodeFixer#27]
This is a feature request: could you add a `--version` flag, to check which version one is currently running? Or is there a better way to check the version?

**Comment by wapmorgan** [comment]
It has `--version` and `-v` flags.

**Comment by MetalArend** [comment]
Ah, I see, on `dev-master` it has a `--version` and `-v` flag indeed. Returns `unversioned` for now, looking forward to the next release. :D

**Comment by wapmorgan** [comment]
Now works always in **2.0.14** version.

**Comment by MetalArend** [comment]
@wapmorgan Thanks a lot, works like a charm!
