### ISSUE TITLE
False positive on php4 constructors

### ISSUE THREAD

**Issue by pylebecq** [wapmorgan/PhpCodeFixer#28]
Hi,

I tried running PhpCodeFixer on the Elastica library (https://github.com/ruflin/Elastica).
There are a lot of false positive related to usage of php4 constructors.

This library already uses php5 constructors but, in addition, some classes also have a method having the same name.

I think the detection of php4 could be improved by using the same rules written in the RFC that deprecated php4 constructors:

>  PHP 7 will emit E_DEPRECATED whenever a PHP 4 constructor is defined. When the method name matches the class name, the class is not in a namespace, and a PHP 5 constructor (__construct) is not present then an E_DEPRECATED will be emitted. PHP 8 will stop emitting E_DEPRECATED and the methods will not be recognized as constructors.
> 
> PHP 7 will also stop emitting E_STRICT when a method with the same name as the class is present as well as __construct.

Source: https://wiki.php.net/rfc/remove_php4_constructors

**Comment by wapmorgan** [comment]
Hello. Which version of Elastica you tried?

**Comment by pylebecq** [comment]
The last one, 6.0.2.

> Max file size set to: 1.000 MiB
Scanning /project/Elastica-6.0.2 ...

> Folder /project/Elastica-6.0.2
 PHP | File:Line                      |             Type | Issue
 7.0 | /lib/Elastica/Log.php:46       | method_name      | Method name log:Log (@php4_constructors) is deprecated. 
 7.0 | /lib/Elas../M../Search.php:140 | method_name      | Method name search:Search (@php4_constructors) is deprecated. 
 7.0 | /lib/Elastica/Search.php:441   | method_name      | Method name search:Search (@php4_constructors) is deprecated. 

> Total problems: 3
Peak memory usage: 2.859 MB

**Comment by wapmorgan** [comment]
Oh, I see. Really, phpcf is syntax-level checker with few improvements. It does not check other methods or class namespace right now. May be I'll find time to rewrite and make it more in

**Comment by wapmorgan** [comment]
Try phpcf **dev-master** version now
