### ISSUE TITLE
False positive on PHP4 Contructor

### ISSUE THREAD

**Issue by mxaddict** [wapmorgan/PhpCodeFixer#29]
SImilar to the issue I saw, but I have a simple sample:

Sample: `User.php`

```php
<?php

/**
 * Class User
 */
class User
{
	public function user()
	{
		return 'User';
	}
}
```

phpcf result:
```
phpcf --target 7.1 .
Max file size set to: 1.000 MiB
Scanning /home/mxaddict/Projects/temp/phpcf_test ...

Folder /home/mxaddict/Projects/temp/phpcf_test
 PHP | File:Line                             |             Type | Issue
 7.0 | /User.php:8                           | method_name      | Method name user:User (@php4_constructors) is deprecated. 

Total problems: 1
Peak memory usage: 1.342 MB
```

Maybe it's possible to make the check case sensitive? As constructors should be same case as the className if I'm not mistaken.

**Comment by wapmorgan** [comment]
No, the case does not value for this.

**Comment by mxaddict** [comment]
Ahh, so there is no way to get the false positive to go away, shame.

**Comment by wapmorgan** [comment]
> As constructors should be same case as the className if I'm not mistaken.
No, that's not required.

Example in rfc:
```php
class Filter {
    // A constructor in PHP 4 and 5
    function filter($a) {}
}
```

**Comment by mxaddict** [comment]
Yeah, i figured as much from the RFC, that's why i decided to close the issue.
