### ISSUE TITLE
PHP Notice:  Uninitialized string offset: 1 in /home/big_shark/.composer/vendor/wapmorgan/php-code-fixer/src/PhpCodeFixer.php on line 91

### ISSUE THREAD

**Issue by Big-Shark** [wapmorgan/PhpCodeFixer#3]
Hi, I am running tools and get error
PHP Notice:  Uninitialized string offset: 1 in /home/big_shark/.composer/vendor/wapmorgan/php-code-fixer/src/PhpCodeFixer.php on line 91

```PHP
if( ! isset($ini_setting[1]))
{
    var_dump($ini_setting);// RETURN string(1) """
}
```

**Comment by wapmorgan** [comment]
Please update phpcf and try again.

**Comment by Big-Shark** [comment]
The error is still present

**Comment by wapmorgan** [comment]
Please update phpcf and try again.

**Comment by Big-Shark** [comment]
Works well, thank you
