### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError 

### ISSUE THREAD

**Issue by Evil85** [wapmorgan/PhpCodeFixer#33]
My Enviroment :
Ubuntu 18.04
PHP 7.1

> PHP Notice:  Undefined offset: 1 in /PhpCodeFixer/data/mb_ereg_replace_e_modifier.php on line 11
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to wapmorgan\PhpCodeFixer\PhpCodeFixer::divideByComma() must be of the type array, null given, called in /PhpCodeFixer/data/mb_ereg_replace_e_modifier.php on line 11 and defined in /PhpCodeFixer/src/PhpCodeFixer.php:463
Stack trace:
#0 /PhpCodeFixer/data/mb_ereg_replace_e_modifier.php(11): wapmorgan\PhpCodeFixer\PhpCodeFixer::divideByComma(NULL)
#1 /PhpCodeFixer/src/PhpCodeFixer.php(504): wapmorgan\PhpCodeFixer\mb_ereg_replace_e_modifier(Array, 'mb_ereg_replace')
#2 /PhpCodeFixer/src/PhpCodeFixer.php(273): wapmorgan\PhpCodeFixer\PhpCodeFixer::callFunctionUsageChecker('wapmorgan\\PhpCo...', 'mb_ereg_replace', Array)
#3 /PhpCodeFixer/src/PhpCodeFixer.php(142): wapmorgan\PhpCodeFixer\PhpCodeFixer->checkFile('/home/evil85/gi...', Object(wapmorgan in /home/evil85/Development/security-tools/PhpCodeFixer/src/PhpCodeFixer.php on line 463

**Comment by ssudhak** [comment]
I am also facing same issue :(. Any idea when will this get fixed.

**Comment by wapmorgan** [comment]
Check out 2.0.17 version

**Comment by wapmorgan** [comment]
@Evil85 @ssudhak any news?

**Comment by ssudhak** [comment]
@wapmorgan sorry for the delay, will check and let you know

**Comment by wapmorgan** [comment]
@ssudhak so, have you tested it?

**Comment by wapmorgan** [comment]
May be it was fixed when working on #36

**Comment by wapmorgan** [comment]
@ssudhak  Check it out

**Comment by ssudhak** [comment]
@wapmorgan ok will try and let you know

**Comment by wapmorgan** [comment]
If you'd give sample, I test.

**Comment by wapmorgan** [comment]
2.0.18 version should work fine.
