### ISSUE TITLE
Use of undefined constant ARRAY_FILTER_USE_KEY

### ISSUE THREAD

**Issue by vegvarit** [wapmorgan/PhpCodeFixer#34]
Hi,

I tried to use the latest version, but I always got this message:

/home/admin//phpcf-2.0.17.phar -t 7.3 ./modules

PHP Warning:  array_filter() expects at most 2 parameters, 3 given in phar:///home/admin/phpcf-2.0.17.phar/src/PhpCodeFixer.php on line 406
PHP Notice:  Use of undefined constant ARRAY_FILTER_USE_KEY - assumed 'ARRAY_FILTER_USE_KEY' in phar:///home/admin/phpcf-2.0.17.phar/src/PhpCodeFixer.php on line 406

This is a bug, or I make something wrong?

**Comment by vegvarit** [comment]
I will use it on PHP 5.4.45-0+deb7u13, maybe this is the problem. On php 7.1 is working normally. But I would like to check this version before upgrade php to 7.x. How can I do this?

**Comment by wapmorgan** [comment]
Check out *dev-master* branch.

**Comment by wapmorgan** [comment]
Or that zipped phar [phpcf-dev.zip](https://github.com/wapmorgan/PhpCodeFixer/files/3133404/phpcf-dev.zip)

**Comment by wapmorgan** [comment]
Fixed in dev-master.
