### ISSUE TITLE
false positive for each() in namespace

### ISSUE THREAD

**Issue by Jimbolino** [wapmorgan/PhpCodeFixer#35]
``` 
 7.2 | /vendor/guzzlehttp/promises/src/functions.php:222                        | function         | Function each() is deprecated. 
 7.2 | /vendor/guzzlehttp/promises/src/functions.php:257                        | function         | Function each() is deprecated. 
 7.2 | /vendor/guzzlehttp/promises/src/functions.php:313                        | function         | Function each() is deprecated. 
```
The functions in this file are namespaced, so its not the same as \each()
https://github.com/guzzle/promises/blob/master/src/functions.php#L2

Function namespacing in php is really weird, because when each() is being called, it first looks for the function in the current namespace, and if it doesn't exist it will resolve to \each()

**Comment by wapmorgan** [comment]
That requires more deep code analyzing.

**Comment by Jimbolino** [comment]
Yes, you're right. You've implemented your own "parser", but that has many downsides.
For example the current version responds to "each()" but not "each ()", even though this is valid php code.

I've been using "phan" for some time, but your fixer is much more comprehensive.

**Comment by wapmorgan** [comment]
> The functions in this file are namespaced, so its not the same as \each()

That' really hard to implement, so you can just avoid this checks with `--skip-checks=each` option.

> For example the current version responds to "each()" but not "each ()", even though this is valid php code.

Fixed

You can use "phpcf" together with "phan", because they can find different problems.
