### ISSUE TITLE
Outputting errors in stderr instead of stdout

### ISSUE THREAD

**Issue by kkmuffme** [wapmorgan/PhpCodeFixer#37]
Would be great if it could output errors on stderr instead of stdout, so phpcf can be in automated deploy pipelines/CI.

e.g.
phpcf myfile >> /dev/null 2>> error.log

Additionally, having the output in json (or at least somewhat configurable) would be great too

**Comment by wapmorgan** [comment]
You can check for exitCode: if any problem found, it will be `-1`

**Comment by kkmuffme** [comment]
Yeah but by that time it is too late if I want to echo the output to a log file, so if it contains any data the deploy/CI process will stop & output the error.

**Comment by wapmorgan** [comment]
Streaming info to stderr does not fit into phpcf interaction model. May be using xml output would be good for this. But, really, you can use exit code to stop CI process after analyzing via phpcf.

**Comment by kkmuffme** [comment]
Ok would it be possible to get a json then on stdout (like phpcs offers)?

**Comment by wapmorgan** [comment]
Yeah, check out `dev-master` and use `--output-json[=OUTPUT-JSON]          Path to store json-file with problems found in code.` option. This generates json with output like:
```json
{
    "info_messages": [
        {
            "type": "info",
            "message": "Skipping file \/media\/wapmorgan\/HDD\/\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b\/PhpCodeFixer\/tests\/trait.php due to file size limit."
        }
    ],
    "problems": [
        {
            "version": "5.3",
            "file": "\/5.3.php",
            "line": 3,
            "type": "ini",
            "checker": "define_syslog_variables"
        }
    ],
    "repalces_suggestions": [
        {
            "type": "function",
            "problem": "mcrypt_generic_end()",
            "replacement": "mcrypt_generic_deinit()"
        }
    ],
    "notes": [
        {
            "type": "function_usage",
            "problem": "piet() (@call_with_passing_by_reference)",
            "note": "Call with passing by reference is deprecated. Problem is \"&$hoho\""
        }
    ]
}
```

**Comment by kkmuffme** [comment]
@wapmorgan perfect. 

Can you include the file path/name in the json too?

Also there is a small spelling mistake: repalces_suggestions => replace_suggestions

**Comment by kkmuffme** [comment]
@wapmorgan ah sorry, didn't see that bc it looks like version above

**Comment by wapmorgan** [comment]
Added `path` field to `problems` sections with full path to file.
Fixed typo - `replace_suggestions` now.

**Comment by kkmuffme** [comment]
Thanks

**Comment by kkmuffme** [comment]
I just tested this now and it would be nicer if:
a) the json would be single line (bc easier to process) - so just remove the new lines please
b) it would append to the file instead of overwriting it

That would make it really really easy to include in every CI/CD workflow
(but it's an amazing standalone tool already :-)

**Comment by wapmorgan** [comment]
> bc easier to process

bc - is it a program? 

> it would append to the file instead of overwriting it

What do it for? This makes no sense: when you do new analyze, you need new results. Two json objects on different lines in the same file - is not valid json data.

**Comment by wapmorgan** [comment]
Now, If analyzer found any problem, phpcf returns 1 exit code. If you passed `--output-json`, result will be saved to this file. Then parse it and show)

Or I didn't understand use-case?

**Comment by kkmuffme** [comment]
I already worked around it & got it integrated :-)

Anyway the original use case was:
a) bc I can just parse 1 line (or parse a file line by line) instead of having to parse the whole file
b) yes it would make the json invalid, however when checking many files it easier to write the whole output to the same file and then just read this file line by line (e.g. how it can be done with psalm, phpcs,...)
