### ISSUE TITLE
No error message / error code when source file is too large

### ISSUE THREAD

**Issue by danielmarschall** [wapmorgan/PhpCodeFixer#39]
I found out that if a source file is larger than the limit, there is no error message, and the exit code is still 0.

The only clue that something is not correct is that the string "Analyzer has not detected any problems in your code." is missing.

> $ ./phpcf.phar /daten/homes/phpmyadmin/public_html/vendor/tecnickcom/tcpdf/fonts/cid0cs.php
> Max file size set to: 1.000 MiB
> Peak memory usage: 2.656 MB
> 
> $ echo $?
> 0
> 
> $ ./phpcf.phar --max-size 2000000 /daten/homes/phpmyadmin/public_html/vendor/tecnickcom/tcpdf/fonts/cid0cs.php
> Max file size set to: 1.907 MiB
> 
> File cid0cs.php
> 
> Analyzer has not detected any problems in your code.
> Peak memory usage: 206.372 MB
>

**Comment by wapmorgan** [comment]
Hmm.. I'm not sure that error is a good way for this. File size limit is purposed to skip files above specific size. If you need to parse a big file, increase `--max-size`.

**Comment by danielmarschall** [comment]
Thank you for your reply. 

There are a few files included in phpmyadmin and other tools which are 1.4 MB. They contain Unicode lookup-tables and stuff.

If a file was skipped, then I think it would be good if there is a notice that your program did so.
The problem is that there is no error message, but no sucess message either.
There is no hint about what happened (e.g. was the file skipped completely? or was just the first megabyte of the file checked etc.?).

**Comment by wapmorgan** [comment]
Ok, I'll add information about skipped files.

**Comment by wapmorgan** [comment]
Added in 2.0.18.
