### ISSUE TITLE
PHP Warning:  Unexpected character in input:  '' (ASCII=31) state=0 in /usr/local/php/vendor/wapmorgan/php-code-fixer/src/PhpCodeFixer.php on line 63

### ISSUE THREAD

**Issue by tiaro** [wapmorgan/PhpCodeFixer#4]
Hi!
I have lots of strings like

```
PHP Warning:  Unexpected character in input:  '' (ASCII=1) state=0 in  /usr/local/php/vendor/wapmorgan/php-code-fixer/src/PhpCodeFixer.php on line 63
PHP Warning:  Unexpected character in input:  '' (ASCII=6) state=0 in  /usr/local/php/vendor/wapmorgan/php-code-fixer/src/PhpCodeFixer.php on line 63
PHP Warning:  Unexpected character in input:  '' (ASCII=22) state=0 in  /usr/local/php/vendor/wapmorgan/php-code-fixer/src/PhpCodeFixer.php on line 63
```

and so on. ASCII=`<number>` where `<number>` changes many times.

**Comment by wapmorgan** [comment]
Please try new commits.

**Comment by tiaro** [comment]
what do you mean? I've updated code by composer - no changes at all.

**Comment by wapmorgan** [comment]
That's strange. Because phpcf should work only against *.php files which does not contain non-printable ascii characters.
Do you launch phpcf to work with a folder? In this case, can you launch it to work with one file at once and thus find out that file containing some control characters?

**Comment by wapmorgan** [comment]
Any news?

**Comment by wapmorgan** [comment]
If you still have this problem, reopen issue.
