### ISSUE TITLE
Dont report on ini_get

### ISSUE THREAD

**Issue by kkmuffme** [wapmorgan/PhpCodeFixer#41]
It should only report on ini_set, not on ini_get

As ini_get does not change anything, thus it is 100% safe to check for deprecated things.

e.g. 

```
$overloaded = function_exists( 'mb_internal_encoding' ) && ( ini_get( 'mbstring.func_overload' ) & 2 );
```

throws:
INI directive 'mbstring.func_overload' is deprecated since PHP 7.2

But it shouldn't.

**Comment by wapmorgan** [comment]
I don't agree, because your code should not rely on these ini-settings.

**Comment by kkmuffme** [comment]
The app/code has to support a wide variety of PHP versions, from PHP 5.6-7.3 on loads of different hosts.

Thus being able to check if an ini is set, with ini_get, but NOT using ini_set to change of it, should be perfectly valid?
I mean the purpose of checking compatibility with phpcf is to see if there are any errors/problems to be expected with a newer version.
But with ini_get there shouldn't be any issue whatsoever I guess?

**Comment by wapmorgan** [comment]
Ok, I understand. Removed `ini_get()` from check-list.
