### ISSUE TITLE
Json output not reflect relations between problem notes and suggestion

### ISSUE THREAD

**Issue by tennsk** [wapmorgan/PhpCodeFixer#43]
Hello Sergey

JSON output is not well formatted, there is no relation between issues and notes/suggestion.
And it can't be parsed correctly because if $issue[2] is empty json element for issue not creates, and data are shifting. There is no perforating id, or something else, in issue and notes/suggestion to correlate it.
https://github.com/wapmorgan/PhpCodeFixer/blob/master/src/ScanCommand.php#L542

Thanks,
Mikhail.

**Comment by wapmorgan** [comment]
Hi, first of all, thanks for Feedback.
Notes/replace suggestions are not inteded to correlate, they are independent objects.
Issues list could be used alone, without notes/RS section.

**Comment by tennsk** [comment]
Ok =) 
I just try to generate HTML report from JSON, but can't do the same output as in text, will parse it.

**Comment by wapmorgan** [comment]
Right now format is described in https://github.com/wapmorgan/PhpCodeFixer#json-report-format.
I will embed notes/replace_suggestions into problems in near future.
