### ISSUE TITLE
Support for PHP 7.4

### ISSUE THREAD

**Issue by kkmuffme** [wapmorgan/PhpCodeFixer#45]
PHP7.4 will be released in 3 weeks and it would be great if phpcf could support it already now.

The list of (breaking) changes can be found here:
https://www.php.net/manual/en/doc.changelog.php
https://www.php.net/manual/en/migration74.php

Thanks a lot!

**Comment by wapmorgan** [comment]
Added in dev-master.

**Comment by kkmuffme** [comment]
Thanks, looks good, please release it.

**Comment by wapmorgan** [comment]
https://github.com/wapmorgan/PhpCodeFixer/releases/tag/2.0.21

**Comment by kkmuffme** [comment]
Thanks, is it possible to get it as a .phar too? (like 2.0.19 and previous versions have)

**Comment by wapmorgan** [comment]
Added, check it out on the release page.

**Comment by kkmuffme** [comment]
Perfect thanks, tested it now, but there are 3 small issues:

1) phpcf -t 7.4 myfile.php I get error:
Target version is not valid. Available target version: 5.3, 5.4, 5.5, 5.6, 7.0, 7.1, 7.2, 7.3

2) can we bump the default version of phpcf to 7.4 (currently 7.3)
(perhaps also update it in the docs)

3) would it be possible to implement a phpcf -v (or --version) which returns the phpcf version number, as currently there is no way to identify which version one has installed?

**Comment by wapmorgan** [comment]
Oh, sorry for late response.
1. Fixed
2. Default version changed to 7.4
3. Added actual version to `phpcf --version` output

**Comment by kkmuffme** [comment]
@wapmorgan perfect thanks.

Fyi in the readme it still has 7.3
