### ISSUE TITLE
Excluding files with -e option don't work

### ISSUE THREAD

**Issue by hdcore** [wapmorgan/PhpCodeFixer#48]
I see in the usage documentation on https://github.com/wapmorgan/PhpCodeFixer:

Options:
    -e, --exclude[=EXCLUDE]                  Sets excluded **file** or **directory** names for scanning. If need to pass few names, join it with comma.

But it don't work for filenames, it only works for directories.

In your PhpCodeFixer class in function checkDirInteral (line 143) I see only the check for the foldername as an exclusion and not for the filename.

**Comment by davejenx** [comment]
I have been unable to get -e or --exclude working with either files or directories, in phpcf 2.0.22 .

**Comment by wapmorgan** [comment]
Check out 2.0.23 version.

**Comment by wapmorgan** [comment]
@hdcore @davejenx check out latest version

**Comment by hdcore** [comment]
I'm already using the last release where this works with my config. So solved for me.
