### ISSUE TITLE
PHP Fatal error:  Allowed memory size of XXX bytes exhausted

### ISSUE THREAD

**Issue by infectormp** [wapmorgan/PhpCodeFixer#5]
Hello.

When i scan some source at my host i get 2 times PHP Fatal error
at 128MB memory limit:
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /xxx/PhpCodeFixer.php on line 63

at 256MB memory limit:
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 524288 bytes) in /xxx/PhpCodeFixer.php on line 40

after i set memory limit for php to 512MB i not get this errors.

**Comment by wapmorgan** [comment]
[ ] Do some tests with large php files

**Comment by wapmorgan** [comment]
I'll look if I could add some tweaks to improve memory consumption.

**Comment by wapmorgan** [comment]
Can you tell what script are you checking?

**Comment by infectormp** [comment]
i check osTciket master branch https://github.com/osTicket/osTicket-1.8

**Comment by infectormp** [comment]
i use php 5.6.13

**Comment by wapmorgan** [comment]
Ok, I've updated phpcf and added option `--max-size` with default value `1mb`. This option sets what file is considered too big and should be skipped. You can use `mb`, `kb` and `gb` suffixes in this option to set another size limit.

For example, you can increase your `memory_limit` option in php config and then increase file size limit like this:
```
php bin/phpcf --max-size 1gb ../osTicket
```

@infectormp, now try to check your script again and write down the results.

**Comment by infectormp** [comment]
Work fine. Thank you.

**Comment by infectormp** [comment]
877Kb file get out of memory ```Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /xxx/PhpCodeFixer.php on line 12```

maybe need set default size to 512Kb

**Comment by infectormp** [comment]
btw, php 7 not have this issue. Peak memory usage: 69.315 MB @ 877 Kb file.
