### ISSUE TITLE
Uninitialized string offset with --target 7.0-experimental

### ISSUE THREAD

**Issue by infectormp** [wapmorgan/PhpCodeFixer#6]
Hello, i have this notice when use --target 7.0-experimental to scan source

```PHP Notice:  Uninitialized string offset: 1 in /xxx/PhpCodeFixer.php on line 162```

**Comment by wapmorgan** [comment]
What script exactly are you checking?

**Comment by wapmorgan** [comment]
Can you show what source exactly are you checking?

**Comment by infectormp** [comment]
I check devnext branch of osTicket https://github.com/osTicket/osTicket-1.8/tree/develop-next

**Comment by wapmorgan** [comment]
Ok, I've updated phpcf and in bd9f0b7fe7ead463602bd15726502cc88b1ce8cd commit fixed this error. Please check and tell about the results.

**Comment by infectormp** [comment]
Work fine. Thank you.
