### ISSUE TITLE
No end of line @ Peak memory usage

### ISSUE THREAD

**Issue by infectormp** [wapmorgan/PhpCodeFixer#7]
With new release PhpCodeFixer show Peak memory usage with some symbol at end of line @ fish  shell 
![123](https://cloud.githubusercontent.com/assets/9958813/10307802/3ada2fc4-6c3a-11e5-8635-012bdbdfe999.PNG)

and no end of line @ bash shell
![bash_old](https://cloud.githubusercontent.com/assets/9958813/10307926/195f5332-6c3b-11e5-8f7b-4df0a354eeaa.PNG)

adding end of line here > ```echo 'Peak memory usage: '.size_format('%.3F U', memory_get_peak_usage(), 'mb') . "\n";```  will fix this
![bash_new](https://cloud.githubusercontent.com/assets/9958813/10307957/5024f7c8-6c3b-11e5-847f-19375797eb94.PNG)

**Comment by wapmorgan** [comment]
Ok, I've updated script so it prints newline char.
