### ISSUE TITLE
--target 7.0

### ISSUE THREAD

**Issue by keradus** [wapmorgan/PhpCodeFixer#8]
There is `--target 7.0-experimental`, but PHP 7 is stable now, any chances to support it as well ?

**Comment by wapmorgan** [comment]
Yes, I'll add full support for 7.0 and 7.1 in future. But now I have no chances to get PC.

**Comment by wapmorgan** [comment]
Changed in 16cfd2482c0a66d0872557a3d39b5d7841e8fd46
