### ISSUE TITLE
php 7.1 support

### ISSUE THREAD

**Issue by infectormp** [wapmorgan/PhpCodeFixer#9]
any plan to support php 7.1?

**Comment by wapmorgan** [comment]
Yes, of course. As soon as possible updates will be done. But at this moment I have no any normal device to update PhpCodeFixer. (I write this comment on very old Nokia 6303).

**Comment by wapmorgan** [comment]
Partially implemented in 16cfd2482c0a66d0872557a3d39b5d7841e8fd46
